#pragma once

#ifdef _DEBUG
	#define KWAK_FIX_ALT_KEYDOWN_MENU_BLOCK
#endif // _DEBUG

//#define NEW_PROTOCOL_SYSTEM

#define PJH_NEW_SERVER_SELECT_MAP

#define ASG_ADD_GENS_SYSTEM
#ifdef ASG_ADD_GENS_SYSTEM
	#define ASG_ADD_INFLUENCE_GROUND_EFFECT
	#define ASG_ADD_GENS_MARK
	#define PBG_MOD_STRIFE_GENSMARKRENDER
	#define PBG_ADD_GENSRANKING
#endif	// ASG_ADD_GENS_SYSTEM

#define KJH_PBG_ADD_INGAMESHOP_SYSTEM
#ifdef KJH_PBG_ADD_INGAMESHOP_SYSTEM
	#define PBG_ADD_INGAMESHOP_UI_MAINFRAME
	#define PBG_ADD_INGAMESHOP_UI_ITEMSHOP
	#define PBG_ADD_NAMETOPMSGBOX
	#define KJH_ADD_INGAMESHOP_UI_SYSTEM
	#define KJH_ADD_PERIOD_ITEM_SYSTEM
	#define PBG_ADD_INGAMESHOPMSGBOX
	#define PBG_ADD_ITEMRESIZE
	#define KJH_MOD_SHOP_SCRIPT_DOWNLOAD
	//^#define PBG_ADD_CHARACTERSLOT
	#define PBG_ADD_CHARACTERCARD
	//^#define LDK_ADD_INGAMESHOP_LIMIT_MOVE_WINDOW
#endif //KJH_PBG_ADD_INGAMESHOP_SYSTEM

#define PJH_ADD_PANDA_PET
#define PJH_ADD_PANDA_CHANGERING
#define PBG_ADD_NEWCHAR_MONK
#define PBG_ADD_NEWCHAR_MONK_ANI
#define PBG_ADD_NEWCHAR_MONK_ITEM
#define PBG_ADD_NEWCHAR_MONK_SKILL
#define LJH_ADD_SYSTEM_OF_EQUIPPING_ITEM_FROM_INVENTORY

//#define EFFECT_MNG_HANDLE

#define IMPLEMENT_IMGUI_WIN32
#define SOCKET_LAUNCHER
#define SYSTEM_OPTION_RENDER
#define SAVE_ACCOUNT_SYSTEM
#define SYSTEM_FLAG_NAT
#define ITEM_CHAT_SELL_SYSTEM
#define EFFECT_KERNEL_VERTEX
#define MAX_INSTANCE_GAME
#define SHUTDOWN_LEVEL_WING3
#define SHUTDOWN_CHARACTER_INFO
#define SHUTDOWN_CORE_WING4
//#define SHUTDOWN_EFFECT_NEW
#define SHUTDOWN_EFFECT_TIMING

//#define PLAYER_INFO_SYSTEM
#define SHUTDOWN_SCALEFORM_INFO

//#define KERNEL_KEY
//#define fps_new_system


#if MAIN_UPDATE==903
#define test_main_dev
#endif // MAIN_UPDATE!=303

#ifdef CHINESE_LANGUAGE
#define CHINESE_CP (0x3A8)
#endif


#define WIN_WINDOW_SIZEX			190
#define WIN_WINDOW_SIZEY			429
#define TURBOJPEG_STATIC
#define ANISOTROPY_FUNCTIONAL
#define SHADER_VERSION_TEST
#if MAIN_UPDATE > 303
//#define V_SYNCRONIZE
//#define WISSPER_CHAT_BLOCKED
#endif // MAIN_UPDATE > 303


#define CB_GETMIXRATE							1
#define CB_DANGKYINGAME							1
