// SkillManager.h: interface for the CSkillManager class.
//////////////////////////////////////////////////////////////////////
#pragma once

enum ActionSkillType
{
	AT_SKILL_POISON			= 1,
	AT_SKILL_METEO			= 2,
	AT_SKILL_THUNDER		= 3,
	AT_SKILL_FIREBALL		= 4,
	AT_SKILL_FLAME			= 5,
	AT_SKILL_TELEPORT		= 6,
	AT_SKILL_SLOW			= 7,
	AT_SKILL_STORM			= 8,
	//Skill_Evil_Spirit			= 9,
	AT_SKILL_HELL			= 10,
	AT_SKILL_POWERWAVE		= 11,
	AT_SKILL_FLASH			= 12,
	AT_SKILL_BLAST			= 13,
	AT_SKILL_INFERNO		= 14,
	AT_SKILL_TELEPORT_B		= 15,
	AT_SKILL_WIZARDDEFENSE	= 16,
	AT_SKILL_ENERGYBALL		= 17,
	AT_SKILL_BLAST_POISON		= 38,
	AT_SKILL_BLAST_FREEZE		= 39,
	AT_SKILL_BLAST_HELL			= 40,
	AT_SKILL_BLAST_HELL_BEGIN	= 58,
	AT_SKILL_BLOCKING   = 18,
	AT_SKILL_SWORD1     = 19,
	AT_SKILL_SWORD2     = 20,
	AT_SKILL_SWORD3     = 21,
	AT_SKILL_SWORD4     = 22,
	AT_SKILL_SWORD5     = 23,
	//Skill_Impale		= 47,
	AT_SKILL_VITALITY	= 48,
	AT_SKILL_RIDER      = 49,
	AT_SKILL_CROSSBOW   = 24,
	AT_SKILL_BOW        = 25,
	AT_SKILL_HEALING    = 26,
	AT_SKILL_DEFENSE    = 27,
	AT_SKILL_ATTACK     = 28,
	AT_SKILL_SUMMON     = 30,
	AT_SKILL_PARALYZE	= 51,
	AT_SKILL_PIERCING	= 52,
	AT_SKILL_IMPROVE_AG = 53,
	AT_SKILL_BLAST_CROSSBOW4 = 54,
	AT_SKILL_REDUCEDEFENSE	= 55,
	AT_SKILL_ICE_BLADE      = 56,
	AT_SKILL_WHEEL      = 41,
	AT_SKILL_FURY_STRIKE= 42,
	AT_SKILL_ONETOONE	= 43,
	AT_SKILL_RUSH       = 44,
	AT_SKILL_JAVELIN    = 45,
	AT_SKILL_DEEPIMPACT = 46,
	AT_SKILL_ONEFLASH   = 57,
	AT_SKILL_BOSS       = 50,	
	AT_SKILL_COMBO		= 59,
	AT_SKILL_STRONG_PIER        = 60,
	AT_SKILL_LONGPIER_ATTACK,
	AT_SKILL_DARK_HORSE,
	AT_SKILL_PARTY_TELEPORT,
	AT_SKILL_ADD_CRITICAL,
	AT_SKILL_THUNDER_STRIKE,
	AT_SKILL_LONG_SPEAR,
	AT_SKILL_STUN,
	AT_SKILL_REMOVAL_STUN,
	AT_SKILL_MANA,
	AT_SKILL_INVISIBLE,
	AT_SKILL_REMOVAL_INVISIBLE,
	AT_SKILL_REMOVAL_BUFF,
	AT_SKILL_DEATH_CANNON,
	AT_SKILL_SPACE_SPLIT,
	AT_SKILL_BRAND_OF_SKILL,
	AT_SKILL_PLASMA_STORM_FENRIR = 76,
	AT_SKILL_INFINITY_ARROW,
	AT_SKILL_DARK_SCREAM,
	AT_SKILL_EXPLODE,

/*+080*/	AT_IMPROVE_DAMAGE,
/*+081*/	AT_IMPROVE_MAGIC,
/*+082*/	AT_IMPROVE_CURSE,
/*+083*/	AT_IMPROVE_BLOCKING,
/*+084*/	AT_IMPROVE_DEFENSE,
/*+085*/	AT_LUCK,
/*+086*/	AT_LIFE_REGENERATION,
/*+087*/	AT_IMPROVE_LIFE,
/*+088*/	AT_IMPROVE_MANA,
/*+089*/	AT_DECREASE_DAMAGE,
/*+090*/	AT_REFLECTION_DAMAGE,
/*+091*/	AT_IMPROVE_BLOCKING_PERCENT,
/*+092*/	AT_IMPROVE_GAIN_GOLD,
/*+093*/	AT_EXCELLENT_DAMAGE,
/*+094*/	AT_IMPROVE_DAMAGE_LEVEL,
/*+095*/	AT_IMPROVE_DAMAGE_PERCENT,
/*+096*/	AT_IMPROVE_MAGIC_LEVEL,
/*+097*/	AT_IMPROVE_MAGIC_PERCENT,
/*+098*/	AT_IMPROVE_ATTACK_SPEED,
/*+099*/	AT_IMPROVE_GAIN_LIFE,
/*+100*/	AT_IMPROVE_GAIN_MANA,
/*+101*/	AT_IMPROVE_HP_MAX,
/*+102*/	AT_IMPROVE_MP_MAX,
/*+103*/	AT_ONE_PERCENT_DAMAGE,
/*+104*/	AT_IMPROVE_AG_MAX,
/*+105*/	AT_DAMAGE_ABSORB,
/*+106*/	AT_DAMAGE_REFLECTION,
/*+107*/	AT_RECOVER_FULL_LIFE,
/*+108*/	AT_RECOVER_FULL_MANA,
/*+109*/	AT_IMPROVE_CHARISMA,
/*+110*/	AT_IMPROVE_EVADE = 110,

	AT_SKILL_MONSTER_SUMMON = 200,
	AT_SKILL_MONSTER_MAGIC_DEF,
	AT_SKILL_MONSTER_PHY_DEF,
	AT_SKILL_HELLOWIN_EVENT_1	= 205,
	AT_SKILL_HELLOWIN_EVENT_2	= 206,
	AT_SKILL_HELLOWIN_EVENT_3	= 207,
	AT_SKILL_HELLOWIN_EVENT_4	= 208,
	AT_SKILL_HELLOWIN_EVENT_5	= 209,
	AT_SKILL_CURSED_TEMPLE_PRODECTION  = 210,
	AT_SKILL_CURSED_TEMPLE_RESTRAINT   = 211,
	AT_SKILL_CURSED_TEMPLE_TELEPORT    = 212,
//	AT_SKILL_CURSED_TEMPLE_QUICKNESS   = 213,
	AT_SKILL_CURSED_TEMPLE_SUBLIMATION = 213,
	AT_SKILL_ALICE_DRAINLIFE = 214,
	AT_SKILL_ALICE_CHAINLIGHTNING = 215,
	AT_SKILL_ALICE_LIGHTNINGORB = 216,
	AT_SKILL_ALICE_THORNS = 217,
	AT_SKILL_ALICE_BERSERKER = 218,
	AT_SKILL_ALICE_SLEEP = 219,
	AT_SKILL_ALICE_BLIND = 220,
	AT_SKILL_ALICE_WEAKNESS = 221,
	AT_SKILL_ALICE_ENERVATION = 222,
	AT_SKILL_SUMMON_EXPLOSION = 223,
	AT_SKILL_SUMMON_REQUIEM,
	AT_SKILL_SUMMON_POLLUTION = 225,
	AT_SKILL_LIGHTNING_SHOCK = 230,
	AT_SKILL_BLOW_OF_DESTRUCTION = 232,
	AT_SKILL_SWELL_OF_MAGICPOWER = 233,
	AT_SKILL_FLAME_STRIKE = 236,
	AT_SKILL_GIGANTIC_STORM = 237,
	AT_SKILL_RECOVER = 234,
	AT_SKILL_MULTI_SHOT = 235,
	AT_SKILL_GAOTIC = 238,
	AT_SKILL_DOPPELGANGER_SELFDESTRUCTION = 239,
	AT_SKILL_THRUST = 260,				// Rage fighter
	AT_SKILL_STAMP = 261,				// Rage fighter
	AT_SKILL_GIANTSWING = 262,			// Rage fighter
	AT_SKILL_DARKSIDE = 263,			// Rage fighter
	AT_SKILL_DRAGON_LOWER = 264,		// Rage fighter
	AT_SKILL_DRAGON_KICK = 265,			// Rage fighter
	AT_SKILL_ATT_UP_OURFORCES = 266,	// Rage fighter
	AT_SKILL_HP_UP_OURFORCES = 267,		// Rage fighter
	AT_SKILL_DEF_UP_OURFORCES = 268,	// Rage fighter
	AT_SKILL_OCCUPY = 269,				// Rage fighter

	Skill_Poison = 1,
	Skill_Meteorite = 2,
	Skill_Lightning = 3,
	Skill_Fire_Ball = 4,
	Skill_Flame = 5,
	Skill_Teleport = 6,
	Skill_Ice = 7,
	Skill_Twister = 8,
	Skill_Evil_Spirit = 9,
	Skill_Hellfire = 10,
	Skill_Power_Wave = 11,
	Skill_Aqua_Beam = 12,
	Skill_Cometfall = 13,
	Skill_Inferno = 14,
	Skill_Teleport_Ally = 15,
	Skill_Soul_Barrier = 16,
	Skill_Energy_Ball = 17,
	Skill_Defense = 18,
	Skill_Falling_Slash = 19,
	Skill_Lunge = 20,
	Skill_Uppercut = 21,
	Skill_Cyclone = 22,
	Skill_Slash = 23,
	Skill_Triple_Shot = 24,
	Skill_Heal = 26,
	Skill_Greater_Defense = 27,
	Skill_Greater_Damage = 28,
	Skill_Summon_Goblin = 30,
	Skill_Summon_Stone_Golem = 31,
	Skill_Summon_Assassin = 32,
	Skill_Summon_Elite_Yeti = 33,
	Skill_Summon_Dark_Knight = 34,
	Skill_Summon_Bali = 35,
	Skill_Summon_Soldier = 36,
	Skill_Decay = 38,
	Skill_Ice_Storm = 39,
	Skill_Nova = 40,
	Skill_Twisting_Slash = 41,
	Skill_Rageful_Blow = 42,
	Skill_Death_Stab = 43,
	Skill_Crescent_Moon_Slash = 44,
	Skill_Lance = 45,
	Skill_Starfall = 46,
	Skill_Impale = 47,
	Skill_Swell_Life = 48,
	Skill_Fire_Breath = 49,
	Skill_Flame_of_Evil = 50,
	Skill_Ice_Arrow = 51,
	Skill_Penetration = 52,
	Skill_Improve_ag = 53,
	Skill_Fire_Slash = 55,
	Skill_Power_Slash = 56,
	Skill_Spiral_Slash = 57,
	Skill_Nova_begin = 58,
	Skill_Combo = 59,
	Skill_Force = 60,
	Skill_Fire_Burst = 61,
	Skill_Earthshake = 62,
	Skill_Summon = 63,
	Skill_Increase_Critical_Damage = 64,
	Skill_Electric_Spike = 65,
	Skill_Force_Wave = 66,
	Skill_Stun = 67,
	Skill_Cancel_Stun = 68,
	Skill_Swell_Mana = 69,
	Skill_Invisibility = 70,
	Skill_Cancel_Invisibility = 71,
	Skill_Abolish_Magic = 72,
	Skill_Mana_Rays = 73,
	Skill_Fire_Blast = 74,
	Skill_Brand = 75,
	Skill_Plasma_Storm = 76,
	Skill_Infinity_Arrow = 77,
	Skill_Fire_Scream = 78,
	Skill_Explosion = 79,
	Skill_PetRaven_Default = 120,
	Skill_PetRaven_Rand = 121,
	Skill_PetRaven_Owner = 122,
	Skill_PetRaven_Target = 123,
	Skill_Summon_Monster = 200,
	Skill_Magic_Attack_Immunity = 201,
	Skill_Physical_Attack_Immunity = 202,
	Skill_Potion_of_Bless = 203,
	Skill_Potion_of_Soul = 204,
	Skill_Spell_of_Protection = 210,
	Skill_Spell_of_Restriction = 211,
	Skill_Spell_of_Pursuit = 212,
	Skill_Shied_Burn = 213,
	Skill_Drain_Life = 214,
	Skill_Chain_Lightning = 215,
	Skill_Electric_Surge = 216,
	Skill_Damage_Reflection = 217,
	Skill_Berserker = 218,
	Skill_Sleep = 219,
	Skill_Weakness = 221,
	Skill_Innovation = 222,
	Skill_Explosion_Sahamutt = 223,
	Skill_Requiem = 224,
	Skill_Pollution = 225,
	Skill_Lightning_Shock = 230,
	Skill_Strike_of_Destruction = 232,
	Skill_Expansion_of_Wizardry = 233,
	Skill_Recovery = 234,
	Skill_Multi_Shot = 235,
	Skill_Flame_Strike = 236,
	Skill_Gigantic_Storm = 237,
	Skill_Chaotic_Diseier = 238,
	Skill_Doppeganger_Self_Explosion_Skil = 239,
	Skill_Magical_Shot = 240,
	Skill_Shining_Bird = 241,
	Skill_Dragon_Violent = 242,
	Skill_Spear_Storm = 243,
	Skill_Reflection_Barrier = 244,
	Skill_Marvel_Burst = 245,
	Skill_Unleash_Marvel = 246,
	Skill_Ultimate_Force = 247,
	Skill_Reflection_Barrier_Reflection = 248,
	Skill_Killing_Blow = 260,
	Skill_Beast_Uppercut = 261,
	Skill_Chain_Drive = 262,
	Skill_Dark_Side = 263,
	Skill_Dragon_Roar = 264,
	Skill_Dragon_Slasher = 265,
	Skill_Ignore_Defense = 266,
	Skill_Increase_Health = 267,
	Skill_Increase_Block = 268,
	Skill_Charge = 269,
	Skill_Phoenix_Shot = 270,

	Skill_Durability_Reduction = 300,
	Skill_PvP_Defence_Rate_Increase = 301,
	Skill_Maximum_SD_increase = 302,
	Skill_Auto_Mana_Recovery_Increase = 303,
	Skill_Poison_Resistance_Increase = 304,
	Skill_Durability_Reduction_2 = 305,
	Skill_SD_Recovery_Speed_Increase = 306,
	Skill_Automatic_HP_Recovery_Increase = 307,
	Skill_Lightning_Resistance_Increase = 308,
	Skill_Defense_Increase = 309,
	Skill_Automatic_AG_Recovery_Increase = 310,
	Skill_Ice_Resistance_Increase = 311,
	Skill_Durability_Reduction_3 = 312,
	Skill_Defense_Success_Rate_Increase = 313,
	Skill_Cast_Invincibility = 314,
	Skill_Armor_Set_Bonus_Increase = 315,
	Skill_Vengeance = 316,
	Skill_Energy_Increase = 317,
	Skill_Stamina_Increase = 318,
	Skill_Agility_Increase = 319,
	Skill_Strength_Increase = 320,
	Skill_Wing_of_Storm_Absorption_PowUp = 321,
	Skill_Wing_of_Storm_Defense_PowUp = 322,
	Skill_Iron_Defense = 323,
	Skill_Wing_of_Storm_Attack_PowUp = 324,
	Skill_Attack_Success_Rate_Increase = 325,
	Skill_Cyclone_Strengthener = 326,
	Skill_Slash_Strengthener = 327,
	Skill_Falling_Slash_Strengthener = 328,
	Skill_Lunge_Strengthener = 329,
	Skill_Twisting_Slash_Strengthener = 330,
	Skill_Anger_Blow_Strengthener = 331,
	Skill_Twisting_Slash_Mastery = 332,
	Skill_Anger_Blow_Mastery = 333,
	Skill_Maximum_Life_Increase = 334,
	Skill_Weapon_Mastery = 335,
	Skill_Death_Stab_Strengthener = 336,
	Skill_Strike_of_Destruction_Strengthe = 337,
	Skill_Maximum_Mana_Increase = 338,
	Skill_Death_Stab_Proficiency = 339,
	Skill_Strike_of_Destruction_Proficien = 340,
	Skill_Maximum_AG_Increase = 341,
	Skill_Death_Stab_Mastery = 342,
	Skill_Strike_of_Destruction_Mastery = 343,
	Skill_Blood_Storm = 344,
	Skill_Combo_Strengthener = 345,
	Skill_Blood_Storm_Strengthener = 346,
	Skill_Attack_Rate = 347,
	Skill_Two_handed_Sword_Strengthener = 348,
	Skill_One_handed_Sword_Strengthener = 349,
	Skill_Mace_Strengthener = 350,
	Skill_Spear_Strengthener = 351,
	Skill_Two_handed_Sword_Mastery = 352,
	Skill_One_handed_Sword_Mastery = 353,
	Skill_Mace_Mastery = 354,
	Skill_Spear_Mastery = 355,
	Skill_Swell_Life_Strengthener = 356,
	Skill_Mana_Reduction = 357,
	Skill_Monster_Attack_SD_Increment = 358,
	Skill_Monster_Attack_Life_Increment = 359,
	Skill_Swell_Life_Proficiency = 360,
	Skill_Minimum_Attack_Power_Increase = 361,
	Skill_Monster_Attack_Mana_Increment = 362,
	Skill_Swell_Life_Mastery = 363,
	Skill_Maximum_Attack_Power_Increase = 364,
	Skill_Increases_critical_damage_rate = 366,
	Skill_Restores_all_Mana = 367,
	Skill_Restores_all_HP = 368,
	Skill_Increases_excellent_damage_rate = 369,
	Skill_Increases_double_damage_rate = 370,
	Skill_Increases_chance_of_ignore_Def = 371,
	Skill_Restores_all_SD = 372,
	Skill_Increases_triple_damage_rate = 373,
	Skill_Eternal_Wings_Absorption_PowUp = 374,
	Skill_Eternal_Wings_Defense_PowUp = 375,
	Skill_Eternal_Wings_Attack_PowUp = 377,
	Skill_Flame_Strengthener = 378,
	Skill_Lightning_Strengthener = 379,
	Skill_Expansion_of_Wizardry_Power_Up = 380,
	Skill_Inferno_Strengthener = 381,
	Skill_Blast_Strengthener = 382,
	Skill_Expansion_of_Wizardry_Mastery = 383,
	Skill_Poison_Strengthener = 384,
	Skill_Evil_Spirit_Strengthener = 385,
	Skill_Magic_Mastery = 386,
	Skill_Decay_Strengthener = 387,
	Skill_Hellfire_Strengthener = 388,
	Skill_Ice_Strengthener = 389,
	Skill_Meteor_Strengthener = 390,
	Skill_Ice_Storm_Strengthener = 391,
	Skill_Nova_Strengthener = 392,
	Skill_Ice_Storm_Mastery = 393,
	Skill_Meteor_Mastery = 394,
	Skill_Nova_Cast_Strengthener = 395,
	Skill_One_handed_Staff_Strengthener = 397,
	Skill_Two_handed_Staff_Strengthener = 398,
	Skill_Shield_Strengthener = 399,
	Skill_One_handed_Staff_Mastery = 400,
	Skill_Two_handed_Staff_Mastery = 401,
	Skill_Shield_Mastery = 402,
	Skill_Soul_Barrier_Strengthener = 403,
	Skill_Soul_Barrier_Proficiency = 404,
	Skill_Minimum_Wizardry_Increase = 405,
	Skill_Soul_Barrier_Mastery = 406,
	Skill_Maximum_Wizardry_Increase = 407,
	Skill_Illusion_Wings_Absorption_PowUp = 409,
	Skill_Illusion_Wings_Defense_PowUp = 410,
	Skill_Multi_Shot_Strengthener = 411,
	Skill_Illusion_Wings_Attack_PowUp = 412,
	Skill_Heal_Strengthener = 413,
	Skill_Triple_Shot_Strengthener = 414,
	Skill_Summoned_Monster_Power_Up1 = 415,
	Skill_Penetration_Strengthener = 416,
	Skill_Defense_Increase_Strengthener = 417,
	Skill_Triple_Shot_Mastery = 418,
	Skill_Summoned_Monster_Power_Up2 = 419,
	Skill_Attack_Increase_Strengthener = 420,
	Skill_Attack_Increase_Mastery = 422,
	Skill_Defense_Increase_Mastery = 423,
	Skill_Ice_Arrow_Strengthener = 424,
	Skill_Cure = 425,
	Skill_Party_Healing = 426,
	Skill_Poison_Arrow = 427,
	Skill_Summoned_Monster_Power_Up3 = 428,
	Skill_Party_Healing_Strengthener = 429,
	Skill_Bless = 430,
	Skill_Multi_Shot_Mastery = 431,
	Skill_Summon_Satyros = 432,
	Skill_Bless_Strengthener = 433,
	Skill_Poison_Arrow_Strengthener = 434,
	Skill_Bow_Strengthener = 435,
	Skill_Crossbow_Strengthener = 436,
	Skill_Bow_Mastery = 438,
	Skill_Crossbow_Mastery = 439,
	Skill_Infinity_Arrow_Strengthener = 441,
	Skill_Dimension_Wings_Absorb_PowUp = 445,
	Skill_Dimension_Wings_Defense_PowUp = 446,
	Skill_Dimension_Wings_Attack_PowUp = 447,
	Skill_Fire_Tome_Strengthener = 448,
	Skill_Wind_Tome_Strengthener = 449,
	Skill_Lightning_Tome_Strengthener = 450,
	Skill_Fire_Tome_Mastery = 451,
	Skill_Earth_Tome_Mastery = 452,
	Skill_Wind_Tome_Mastery = 453,
	Skill_Sleep_Strengthener = 454,
	Skill_Chain_Lightning_Strengthener = 455,
	Skill_Lightning_Shock_Strengthener = 456,
	Skill_Drain_Life_Strengthener = 458,
	Skill_Weakness_Strengthener = 459,
	Skill_Innovation_Strengthener = 460,
	Skill_Blind = 461,
	Skill_Drain_Life_Mastery = 462,
	Skill_Blind_Strengthener = 463,
	Skill_Stick_Strengthener = 465,
	Skill_Other_World_Tome_Strengthener = 466,
	Skill_Stick_Mastery = 467,
	Skill_Other_World_Tome_Mastery = 468,
	Skill_Berserker_Strengthener = 469,
	Skill_Berserker_Proficiency = 470,
	Skill_Minimum_Wizardry_Curse_Increase = 471,
	Skill_Berserker_Mastery = 472,
	Skill_Maximum_Wizardry_Curse_Increase = 473,
	Skill_Wing_of_Ruin_Absorption_PowUp = 475,
	Skill_Wing_of_Ruin_Defense_PowUp = 476,
	Skill_Wing_of_Ruin_Attack_PowUp = 478,
	Skill_Cyclone_Strengthener2 = 479,
	Skill_Lightning_Strengthener2 = 480,
	Skill_Twisting_Slash_Strengthener2 = 481,
	Skill_Power_Slash_Strengthener = 482,
	Skill_Flame_Strengthener2 = 483,
	Skill_Blast_Strengthener2 = 484,
	Skill_Inferno_Strengthener2 = 486,
	Skill_Evil_Spirit_Strengthener2 = 487,
	Skill_Ice_Strengthener2 = 489,
	Skill_Fire_Slash_Strengthener = 490,
	Skill_Ice_Mastery2 = 491,
	Skill_Flame_Strike_Strengthener = 492,
	Skill_Fire_Slash_Mastery = 493,
	Skill_Flame_Strike_Mastery = 494,
	Skill_Earth_Prison = 495,
	Skill_Gigantic_Storm_Strengthener = 496,
	Skill_Earth_Prison_Strengthener = 497,
	Skill_Emperor_Cape_Absorption_PowUp = 504,
	Skill_Emperor_Cape_Defense_PowUp = 505,
	Skill_Adds_Command_Stat = 506,
	Skill_Emperor_Cape_Attack_PowUp = 507,
	Skill_Fire_Burst_Strengthener = 508,
	Skill_Force_Wave_Strengthener = 509,
	Skill_Dark_Horse_Strengthener = 510,
	Skill_Critical_DMG_Increase_PowUp1 = 511,
	Skill_Earthshake_Strengthener = 512,
	Skill_Fire_Burst_Mastery = 514,
	Skill_Critical_DMG_Increase_PowUp2 = 515,
	Skill_Earthshake_Mastery = 516,
	Skill_Critical_DMG_Increase_PowUp3 = 517,
	Skill_Fire_Scream_Strengthener = 518,
	Skill_Electric_Spark_Strengthener = 519,
	Skill_Fire_Scream_Mastery = 520,
	Skill_Critical_DMG_Increase_Mastery = 522,
	Skill_Chaotic_Diseier_Strengthener = 523,
	Skill_Dark_Spirit_Strengthener = 526,
	Skill_Scepter_Strengthener = 527,
	Skill_Use_Scepter_Pet_Strengthener = 529,
	Skill_Dark_Spirit_Strengthener_2 = 530,
	Skill_Scepter_Mastery = 531,
	Skill_Command_Attack_Increase = 533,
	Skill_Dark_Spirit_Strengthener_3 = 534,
	Skill_Pet_Durability_Strengthener = 535,
	Skill_Dark_Spirit_Strengthener_4 = 536,
	Skill_Dark_Spirit_Strengthener_5 = 538,
	Skill_Spirit_Lord = 539,
	Skill_Reigning_Cloak_Absorption_PowUp = 548,
	Skill_Reigning_Cloak_Defense_PowUp = 549,
	Skill_Reigning_Cloak_Attack_PowUp = 550,
	Skill_Killing_Blow_Strengthener = 551,
	Skill_Beast_Uppercut_Strengthener = 552,
	Skill_Killing_Blow_Mastery = 554,
	Skill_Beast_Uppercut_Mastery = 555,
	Skill_Def_Success_Rate_Strengthener = 556,
	Skill_Chain_Drive_Strengthener = 558,
	Skill_Dark_Side_Strengthener = 559,
	Skill_Dragon_Roar_Strengthener = 560,
	Skill_Dragon_Roar_Mastery = 561,
	Skill_Chain_Drive_Mastery = 562,
	Skill_Dark_Side_Mastery = 563,
	Skill_Dragon_Slasher_Strengthener = 564,
	Skill_Blood_Howling = 565,
	Skill_Dragon_Slasher_Mastery = 566,
	Skill_Blood_Howling_Strengthener = 567,
	Skill_Equipped_Weapon_Strengthener = 568,
	Skill_Defense_Success_Rate_Increase_P = 569,
	Skill_Equipped_Weapon_Mastery = 571,
	Skill_DefSuccessRate_Increase_Mastery = 572,
	Skill_Stamina_Increase_Strengthener = 573,
	Skill_Defense_Switch = 574,
	Skill_Increase_PvP_Defense_Rate = 579,
	Skill_Increase_Maximum_SD = 580,
	Skill_Increase_Mana_Recovery_Rate = 581,
	Skill_Increase_Poison_Resistance = 582,
	Skill_Increase_SD_Recovery_Rate = 584,
	Skill_Increase_HP_Recovery_Rate = 585,
	Skill_Increase_Lightning_Resistance = 586,
	Skill_Increases_Defense = 587,
	Skill_Increases_AG_Recovery_Rate = 588,
	Skill_Increase_Ice_Resistance = 589,
	Skill_Increase_Defense_Success_Rate = 591,
	Skill_Increase_Set_Defense = 593,
	Skill_Increase_Energy = 595,
	Skill_Stamina_Increases = 596,
	Skill_Increase_Agility = 597,
	Skill_Increase_Strength = 598,
	Skill_Increase_Attack_Success_Rate = 599,
	Skill_Increase_Maximum_HP = 600,
	Skill_Increase_Maximum_Mana = 601,
	Skill_Increase_Maximum_AG = 602,
	Skill_Increase_PvP_Attack_Rate = 603,
	Skill_Decrease_Mana = 604,
	Skill_Recover_SD_from_Monster_Kills = 605,
	Skill_Recover_HP_from_Monster_Kills = 606,
	Skill_Increase_Minimum_Attack_Power = 607,
	Skill_Recover_Mana_from_Monster_Kills = 608,
	Skill_Increase_Maximum_Attack_Power = 609,
	Skill_Increases_Critical_DMG_Chance = 610,
	Skill_Recover_Mana_Fully = 611,
	Skill_Recovers_HP_Fully = 612,
	Skill_Increase_Excellent_DMG_Chance = 613,
	Skill_Increase_Double_Damage_Chance = 614,
	Skill_Increase_Ignore_Def_Chance = 615,
	Skill_Recovers_SD_Fully = 616,
	Skill_Increase_Triple_Damage_Chance = 617,
};

typedef struct DemendConditionInfo
{
	WORD SkillType;
//	char SkillName[100];
	WORD SkillLevel;
	WORD SkillStrength;
	WORD SkillDexterity;
	WORD SkillVitality;
	WORD SkillEnergy;
	WORD SkillCharisma;
		
	DemendConditionInfo() : SkillType( 0 ), SkillLevel( 0 ), SkillStrength( 0 ),
		SkillDexterity( 0 ), SkillVitality( 0 ), SkillEnergy( 0 ), SkillCharisma( 0 )
	{
//		ZeroMemory( SkillName, 100 );
	}
	BOOL operator<=(const DemendConditionInfo& rhs) const
	{
		return SkillStrength <= rhs.SkillStrength && SkillDexterity <= rhs.SkillDexterity &&
		SkillVitality <= rhs.SkillVitality && SkillEnergy <= rhs.SkillEnergy && SkillCharisma <= rhs.SkillCharisma;
	}
} DemendConditionInfo;

class CSkillManager
{
public:
	CSkillManager();
	virtual ~CSkillManager();
	bool FindHeroSkill(ActionSkillType eSkillType); 
	void GetSkillInformation(int iType, int iLevel, char *lpszName, int *piMana, int *piDistance, int *piSkillMana = NULL);
	void GetSkillInformation_Energy(int iType, int *piEnergy);
	void GetSkillInformation_Charisma(int iType, int *piCharisma);
	float GetSkillDistance(int Index, CHARACTER* c=NULL);
	void GetSkillInformation_Damage(int iType, int *piDamage);
	bool CheckSkillDelay(int SkillIndex);
	void CalcSkillDelay(int time);
	bool IsMultiTargetSkill(int SkillIndex);
	BYTE GetSkillMasteryType (int iType);
	int MasterSkillToBaseSkillIndex(int iMasterSkillIndex);
	bool skillVScharactorCheck( const DemendConditionInfo& basicInfo, const DemendConditionInfo& heroInfo );
	bool DemendConditionCheckSkill(WORD skilltype);
public:

};

extern CSkillManager gSkillManager;